---
abstract: 'WebScraping pseudo-API for iDoneThis'
author:
  - 'Paul Fenwick <pjf@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Idonethis
requires:
  Carp: 0
  Config::Tiny: 0
  File::Spec: 0
  File::XDG: 0
  Getopt::Std: 0
  HTML::Entities: 0
  HTTP::Cookies: 0
  HTTP::Request: 0
  JSON::Any: 0
  LWP::Protocol::https: 0
  Moo: 0
  POSIX: 0
  Pod::Usage: 0
  Try::Tiny: 0
  WWW::Mechanize: 0
  autodie: 0
  constant: 0
  perl: v5.10.0
  strict: 0
  utf8::all: 0
  warnings: 0
resources:
  repository: git://github.com/pfenwick/idonethis-perl
version: 0.13
